### ISSUE TITLE
Allow inline images

### ISSUE THREAD

**Issue by ojack** [hydra-synth/hydra-docs#15]
Would like to have styling similar to github markdown:
![Screenshot 2022-06-03 at 14 19 40](https://user-images.githubusercontent.com/4909769/171852408-b24eb4d7-91d6-4516-aaa2-b95c299f3299.png)
![Screenshot 2022-06-03 at 14 19 46](https://user-images.githubusercontent.com/4909769/171852421-db890d9c-dcbb-42ac-9d66-e0077465a88b.png)

**Comment by micuat** [comment]
I can't come up with an easy solution - maybe using raw HTML tags + class for inline images?

**Comment by ojack** [comment]
Yes! I actually got this working that way so will close now.
