### ISSUE TITLE
sidebar not loaded

### ISSUE THREAD

**Issue by micuat** [hydra-synth/hydra-docs#17]
perhaps due to the recent changes, the sidebar is not loaded

![image](https://github.com/hydra-synth/hydra-docs/assets/1835081/b66c730f-b9ed-4279-88eb-d1d3561e6c14)

**Comment by ojack** [comment]
It seems to exist: https://github.com/hydra-synth/hydra-synth.github.io/tree/gh-pages/docs but is not loaded to the pages site for some reason

**Comment by ojack** [comment]
It is also strange that the other markdown files are loaded. i.e. https://hydra.ojack.xyz/docs/additional_topics.md

but not:  https://hydra.ojack.xyz/docs/_sidebar.md

**Comment by micuat** [comment]
as I mentioned in https://github.com/hydra-synth/hydra-synth.github.io/pull/1 it is specific to the gh-pages subdirectory. closing
