### ISSUE TITLE
Smaller canvas + side-by-side editor?

### ISSUE THREAD

**Issue by ojack** [hydra-synth/hydra-docs#4]
Sometimes I don't see the code at all when scrolling:
<img width="811" alt="Screenshot 2022-03-05 at 11 02 38" src="https://user-images.githubusercontent.com/4909769/156891181-dbb124fa-fc51-45cd-a213-b26126435968.png">
:

Was thinking it could make sense to have a smaller canvas and have the editor on the left side, canvas on the right.

**Comment by micuat** [comment]
side by side editor implemented by 4cd2a6d4658547af14526c455598ae75e9b891e8

still working on smaller canvas - not sure how to detect the optimal size

**Comment by micuat** [comment]
I think the layout is kind of ok for now... please reopen if you have specific wishes
